### ISSUE TITLE
NoMethodError (undefined method `before_validation' for xxx:Class)

### ISSUE THREAD

**Issue by RahulBacancy** [LaunchAcademy/better_date_picker#5]
- I am getting 'after_validation' error when the the code visit ib/better_date_picker/model.rb:21
- Earlier with Ruby 2.3.4 and rails 5.0, the same code was working.
- When I upgraded the version of ruby to 2.5.3 and rails to 5.2.3, I start getting this error of after_validation.
- Can you please upgrade its dependency so that it even works with rails latest version.

**Comment by dpickett** [comment]
hi there @RahulBacancy - can you share your active model class? I am able to run this without issue on ActiveModel 5.2.3 and ruby 2.5.2. Does your class do something like:

```ruby
include ActiveModel::Model
include ActiveModel::Validations::Callbacks
```

My guess is callbacks are not loading in the class, which would result in a `NoMethodError` for `after_validation`
